import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useTypeSafeTranslation } from '../../utils/translationHelper';
import { 
  Card, 
  Button, 
  Input, 
  Form,
  Avatar,
  Divider,
  message
} from 'antd';
import { 
  ArrowLeftOutlined,
  UserOutlined,
  EyeOutlined,
  MessageOutlined,
  SendOutlined
} from '@ant-design/icons';
import StorageSystem, { UserData, Reply } from '../../utils/StorageSystem';
import Layout from '../layout/Layout';
import '../../styles/HelpDetailPage.css';
import { DatabaseService } from '../../services/database.service';
import { Post, Reply as DatabaseReply } from '../../types/database.types';
import ReplyForm from '../ReplyForm';
import { supabase } from '../../lib/supabase';
import { getCurrentUserId } from '../../utils/authHelpers';

const { TextArea } = Input;

// Helper function to get time ago
const getTimeAgo = (timestamp: string): string => {
  const now = new Date();
  const past = new Date(timestamp);
  const diffMs = now.getTime() - past.getTime();
  
  const diffSecs = Math.floor(diffMs / 1000);
  const diffMins = Math.floor(diffSecs / 60);
  const diffHours = Math.floor(diffMins / 60);
  const diffDays = Math.floor(diffHours / 24);
  const diffWeeks = Math.floor(diffDays / 7);
  const diffMonths = Math.floor(diffDays / 30);
  
  if (diffMonths > 0) {
    return diffMonths === 1 ? '1 month ago' : `${diffMonths} months ago`;
  } else if (diffWeeks > 0) {
    return diffWeeks === 1 ? '1 week ago' : `${diffWeeks} weeks ago`;
  } else if (diffDays > 0) {
    return diffDays === 1 ? '1 day ago' : `${diffDays} days ago`;
  } else if (diffHours > 0) {
    return diffHours === 1 ? '1 hour ago' : `${diffHours} hours ago`;
  } else if (diffMins > 0) {
    return diffMins === 1 ? '1 minute ago' : `${diffMins} minutes ago`;
  } else {
    return 'Just now';
  }
};

// Generate a random helper ID
const generateHelperId = (): string => {
  return `Helper #${Math.floor(1000 + Math.random() * 9000)}`;
};

const HelpDetailPage: React.FC = () => {
  const { accessCode } = useParams<{ accessCode: string }>();
  const { t } = useTypeSafeTranslation();
  const [form] = Form.useForm();
  
  const [post, setPost] = useState<Post | null>(null);
  const [replies, setReplies] = useState<DatabaseReply[]>([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [helperId] = useState(generateHelperId());
  const [error, setError] = useState<string | null>(null);
  const [currentUserId, setCurrentUserId] = useState<string | undefined>(undefined);
  
  // Fetch post and replies
  const fetchPostAndReplies = async () => {
    if (!accessCode) {
      setError('Invalid access code');
      setLoading(false);
      return;
    }
    
    try {
      setLoading(true);
      
      // Get post by access code
      const fetchedPost = await DatabaseService.getPostByAccessCode(accessCode);
      
      if (!fetchedPost) {
        setError('Post not found');
        setLoading(false);
        return;
      }
      
      setPost(fetchedPost);
      
      // Get replies for this post
      const fetchedReplies = await DatabaseService.getRepliesByPostId(fetchedPost.id);
      setReplies(fetchedReplies);
      
    } catch (error) {
      console.error('Error fetching post details:', error);
      setError('Failed to load post details');
    } finally {
      setLoading(false);
    }
  };
  
  // Load post and replies on component mount
  useEffect(() => {
    fetchPostAndReplies();
  }, [accessCode]);
  
  // Get the current user ID when the component mounts
  useEffect(() => {
    async function fetchCurrentUser() {
      const userId = await getCurrentUserId();
      setCurrentUserId(userId);
    }
    
    fetchCurrentUser();
  }, []);
  
  // Handle marking a reply as solution
  const handleMarkAsSolution = async (replyId: string) => {
    if (!post) return;
    
    try {
      const success = await DatabaseService.markReplyAsSolution(replyId, post.id);
      
      if (success) {
        // Refresh the replies to show the updated solution status
        fetchPostAndReplies();
      }
    } catch (error) {
      console.error('Error marking reply as solution:', error);
    }
  };
  
  // Handle reply submission
  const handleSubmitReply = async (values: { replyText: string }) => {
    if (!post || !values.replyText.trim()) return;
    
    setSubmitting(true);
    
    try {
      // Get the current user ID
      const userId = await getCurrentUserId();
      
      // Create new reply data (without id, it will be generated by the database)
      const replyData = {
        content: values.replyText,
        is_anonymous: false,
        is_solution: false,
        user_id: userId,
        post_id: post.id
      };
      
      // Add reply to post in Supabase
      await DatabaseService.createReply(replyData);
      
      // Get updated post data
      const updatedPostData = await DatabaseService.getPostByAccessCode(accessCode!);
      setPost(updatedPostData);
      
      // Reset form
      form.resetFields();
      
      // Show success message
      message.success(t('replySubmitted'));
    } catch (error) {
      console.error('Error submitting reply:', error);
      message.error(t('errorSubmittingReply'));
    } finally {
      setSubmitting(false);
    }
  };
  
  if (loading) {
    return (
      <Layout>
        <div className="container help-detail-container">
          <div className="loading-message">{t('loading')}</div>
        </div>
      </Layout>
    );
  }
  
  if (!post) {
    return (
      <Layout>
        <div className="container help-detail-container">
          <div className="error-message">{t('postNotFound')}</div>
          <Link to="/help" className="back-link">
            <ArrowLeftOutlined /> {t('backToHelp')}
          </Link>
        </div>
      </Layout>
    );
  }
  
  return (
    <Layout>
      <div className="container help-detail-container">
        <div className="page-header">
          <Link to="/help" className="back-link">
            <ArrowLeftOutlined /> {t('backToHelp')}
          </Link>
        </div>
        
        <Card className="post-detail-card">
          <div className="post-header">
            <div className="post-meta">
              <span className="post-id">ID: {post.user_id}</span>
              <span className="post-time">{getTimeAgo(post.created_at)}</span>
            </div>
            <div className="post-stats">
              <span className="post-stat">
                <EyeOutlined /> {post.views || 0} {t('views')}
              </span>
              <span className="post-stat">
                <MessageOutlined /> {post.replies?.length || 0} {t('replies')}
              </span>
            </div>
          </div>
          
          <div className="post-title">
            {post.content}
          </div>
          
          <div className="post-tags">
            {post.tags.map(tag => (
              <span key={tag} className="post-tag">{tag}</span>
            ))}
          </div>
          
          <Divider>{t('replies')} ({replies.length})</Divider>
          
          {/* Display replies */}
          <div className="replies-section">
            <h3>{t('replies')} ({replies.length})</h3>
            
            {replies.length === 0 ? (
              <p>{t('noRepliesYet')}</p>
            ) : (
              replies.map(reply => (
                <div key={reply.id} className={`reply ${reply.is_solution ? 'solution' : ''}`}>
                  <div className="reply-content">{reply.content}</div>
                  <div className="reply-meta">
                    <span>{reply.is_anonymous ? t('anonymous') : t('user')}</span>
                    <span>{getTimeAgo(reply.created_at)}</span>
                    
                    {/* Show mark as solution button for post owner */}
                    {post?.user_id === currentUserId && !reply.is_solution && (
                      <Button 
                        size="small" 
                        onClick={() => handleMarkAsSolution(reply.id)}
                      >
                        {t('markAsSolution')}
                      </Button>
                    )}
                    
                    {reply.is_solution && (
                      <span className="solution-badge">{t('solution')}</span>
                    )}
                  </div>
                </div>
              ))
            )}
            
            {/* Reply form */}
            <div className="reply-form-container">
              <h3>{t('addReply')}</h3>
              <ReplyForm 
                postId={post?.id || ''} 
                onReplyAdded={fetchPostAndReplies} 
              />
            </div>
          </div>
        </Card>
      </div>
    </Layout>
  );
};

export default HelpDetailPage; 