name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你的默认分支名称

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 或者你项目使用的 Node.js 版本

      - name: Install Dependencies
        run: npm ci  # 使用 ci 而不是 install 以确保一致性

      - name: Build
        run: npm run build
        env:
          VITE_SIMULATE_GH_PAGES: true
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # Vite 构建输出目录
          branch: gh-pages  # 部署到的分支 